<a href="https://colab.research.google.com/github/019Vipin/mathematics-for-ml/blob/main/Matrix_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Creating a Matrix using numpy

In [ ]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [ ]:
matrix_1.shape

(2, 2)

In [ ]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [ ]:
matrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [ ]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.85794147 0.51086119 0.43444087]
 [0.63459481 0.56397833 0.03425991]
 [0.88948904 0.81956245 0.81811735]]


In [ ]:
# creating matrix with random integers
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[41 36 17  2 39]
 [60  4 22 60 66]
 [92 60 16 73 72]
 [ 6 84 56 73 23]]


Matrix with all the values as 1

In [ ]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [ ]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix or Zero Matrix

In [ ]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity Matrix

In [ ]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a Matrix

In [ ]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[32 30 84 76 36]
 [81 93 49 43 91]
 [63 23 77 10 25]
 [48 81 65 33 64]]


In [ ]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[32 81 63 48]
 [30 93 23 81]
 [84 49 77 65]
 [76 43 10 33]
 [36 91 25 64]]


Importing Numpy Library

In [ ]:
import numpy as np

Matrix Addition

Two Matrices can be added only if they have the same shape

In [ ]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [ ]:
print(A)

[[2 3]
 [4 5]]


In [ ]:
print(B)

[[6 7]
 [8 9]]


In [ ]:
A.shape

(2, 2)

In [ ]:
B.shape

(2, 2)

Adding two Matrices

In [ ]:
sum = A + B

In [ ]:
print(sum)

[[ 8 10]
 [12 14]]


In [ ]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [ ]:
print(matrix_1)

[[7 0 6]
 [6 9 7]
 [4 1 1]]


In [ ]:
print(matrix_2)

[[10  9  8]
 [15 13 19]
 [14 16 17]]


In [ ]:
sum = np.add(matrix_1, matrix_2)

In [ ]:
print(sum)

[[17  9 14]
 [21 22 26]
 [18 17 18]]


In [ ]:
# create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

In [ ]:
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(10, size=(3,3))

sum_2 = np.add(matrix_3, matrix_4)
print(sum_2)

[[11  9 14]
 [11  9  8]
 [ 8 12 12]]


We get this error because shape of matrix_3 and matrix_4 are different

Matrix Subtraction

In [ ]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [ ]:
print(A)

[[2 3]
 [4 5]]


In [ ]:
print(B)

[[6 7]
 [8 9]]


In [ ]:
difference = A - B

In [ ]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [ ]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [ ]:
print(matrix_1)

[[5 1 4]
 [7 9 0]
 [6 8 3]]


In [ ]:
print(matrix_2)

[[11 18  9]
 [19  4  0]
 [18 13  5]]


In [ ]:
diff = np.subtract(matrix_1, matrix_2)

In [ ]:
print(diff)

[[ -6 -17  -5]
 [-12   5   0]
 [-12  -5  -2]]


Multiplying a matrix by a scalar

In [ ]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[4 3 8 4]
 [9 8 0 6]
 [2 6 3 1]
 [3 7 7 9]]


In [ ]:
product = np.multiply(x,y)

In [ ]:
print(product)

[[20 15 40 20]
 [45 40  0 30]
 [10 30 15  5]
 [15 35 35 45]]


Multiplying 2 Matrices

In [ ]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [ ]:
print(matrix_3)

[[3 4 2]
 [4 2 3]
 [3 3 4]]


In [ ]:
print(matrix_4)

[[0 4 3 4]
 [1 0 4 2]
 [0 3 2 2]]


In [ ]:
product = np.dot(matrix_3, matrix_4)

In [ ]:
print(product)

[[ 4 18 29 24]
 [ 2 25 26 26]
 [ 3 24 29 26]]


Element wise Matrix Multiplication

In [ ]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [ ]:
print(matrix_3)

[[0 3 0]
 [2 3 4]
 [2 1 3]]


In [ ]:
print(matrix_4)

[[4 0 4]
 [1 1 3]
 [4 4 4]]


In [ ]:
product = np.multiply(matrix_3, matrix_4)

In [ ]:
print(product)

[[ 0  0  0]
 [ 2  3 12]
 [ 8  4 12]]


In [ ]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [ ]:
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

product = np.multiply(matrix_3, matrix_4)

print(product)

[[ 8  0  0]
 [ 2  0 12]
 [ 2  4  8]]
